# Generated by Django 5.0.6 on 2025-02-06 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_staff_staff_id_staff_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_address', models.TextField(blank=True, null=True)),
                ('postal_city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_region', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_prospect', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_manager_uuid', models.UUIDField(blank=True, null=True)),
                ('account_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_manager_uuid', models.UUIDField(blank=True, null=True)),
                ('job_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_term', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_day', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_client_uuid', models.UUIDField(blank=True, null=True)),
                ('billing_client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('date_created_utc', models.DateTimeField(blank=True, null=True)),
                ('date_modified_utc', models.DateTimeField(blank=True, null=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('manager_uuid', models.UUIDField(blank=True, null=True)),
                ('partner_uuid', models.UUIDField(blank=True, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('salutation', models.CharField(blank=True, max_length=50, null=True)),
                ('addressee', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_minutes', models.IntegerField(blank=True, null=True)),
                ('actual_minutes', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('billable', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobAssignedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_uuid', models.UUIDField()),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assigned_staff', to='main.job')),
            ],
            options={
                'unique_together': {('job', 'staff_uuid')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignedStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_uuid', models.UUIDField()),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('allocated_minutes', models.IntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_staff', to='main.task')),
            ],
            options={
                'unique_together': {('task', 'staff_uuid')},
            },
        ),
    ]
