# Generated by Django 5.0.6 on 2025-02-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_job_contact_task_jobassignedstaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(default=123456, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
