# Generated by Django 5.0.1 on 2025-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager')], default='STAFF', max_length=20),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_uuid', models.UUIDField()),
                ('task_uuid', models.UUIDField()),
                ('job_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'time_entries',
                'ordering': ['-date'],
                'unique_together': {('staff_uuid', 'task_uuid', 'job_id', 'date')},
            },
        ),
    ]
